<Project Sdk="Prometheus.MSBuild.Sdk/0.3.1-beta.1">
  <!--<Import Project="..\..\src\Prometheus.MSBuild\Sdk\Sdk.props" />-->
  <PropertyGroup>
    <ProductName>Net.Tests</ProductName>
    <TargetPlatform>net10.0</TargetPlatform>
    <!--<IsTestProject>True</IsTestProject>-->
    <IsLibraryProject>True</IsLibraryProject>   
    <!--<PrometheusTasksEnabled>false</PrometheusTasksEnabled>-->
  </PropertyGroup>
  <!--k<Import Project="..\..\src\Prometheus.MSBuild\Sdk\Sdk.targets" />-->
</Project>
