<Project>
  <PropertyGroup>
    <PrometheusEnabled Condition="'$(PrometheusEnabled)' == ''" >True</PrometheusEnabled>
    <PrometheusAutoLoad Condition="'$(PrometheusAutoLoad)' == ''">True</PrometheusAutoLoad>
    <PrometheusDirectory Condition="'$(PrometheusDirectory)' == ''">$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), Prometheus.Build.props))</PrometheusDirectory>
    <PrometheusProps Condition="'$(PrometheusProps)' == ''">$(PrometheusDirectory)\Prometheus.Build.props</PrometheusProps>
    <PrometheusTargets Condition="'$(PrometheusTargets)' == ''">$(PrometheusDirectory)\Prometheus.Build.targets</PrometheusTargets>
  </PropertyGroup>
  
  <Import Project="$(PrometheusProps)" Condition="Exists('$(PrometheusProps)')"/>
  <ImportGroup Label="Fallback/Default Known SDKs">
    <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" Condition="'$(IsPackageOnlyProject)' != 'true'" />
    <Import Project="Sdk.props" Sdk="Microsoft.Build.NoTargets" Version="3.7.56" Condition="'$(IsPackageOnlyProject)' == 'true'" />
  </ImportGroup>
</Project>
