<Project>
  <Import Project="Sdk.props" Condition="'$(_SdkPropsLoaded)' != 'true'" />

  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == '' And '$(RuntimeId)' != ''">$(RuntimeId)</TargetFramework>
    <TargetFrameworks Condition="'$(TargetFrameworks)' == '' And '$(TargetPlatforms)' != ''">$(TargetPlatforms)</TargetFrameworks>
    <TargetPlatform Condition="'$(TargetPlatform)' == '' And '$(TargetFramework)' != ''">$(TargetFramework)</TargetPlatform>
  </PropertyGroup>
  
  <Import Project="$(PrometheusTargets)" Condition="Exists('$(PrometheusTargets)')"/>

  <ImportGroup Label="Fallback/Default Known SDKs">
    <!--Condition="'$(PrometheusLoadType)' == 'full' And ('$(TargetFramework)' != '' Or '$(TargetFrameworks)' != '')">-->
    <!--<Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />-->
    <!--<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets"
          Condition="'$(PlatformId)' == 'android' And '$(RuntimeVersion)' &lt;= '5.0'" />-->
    <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" Condition="'$(IsPackageOnlyProject)' != 'true'" />
    <Import Project="Sdk.targets" Sdk="Microsoft.Build.NoTargets" Version="3.7.56"
            Condition="'$(IsPackageOnlyProject)' == 'true'" />
  </ImportGroup>
</Project>
