<Project InitialTargets="_PrintPrometheusDefaultProps">
  <PropertyGroup>
    <PrometheusEnabled Condition="'$(PrometheusEnabled)' == ''" >True</PrometheusEnabled>
    <PrometheusAutoLoad Condition="'$(PrometheusAutoLoad)' == ''">True</PrometheusAutoLoad>
    <UseDefaultFramework>True</UseDefaultFramework>
    <UseDefaultMultiFramework>False</UseDefaultMultiFramework>
    <NetFrameworksLts>
      net10.0;
      net8.0;
      netstandard2.1;
      net48;
    </NetFrameworksLts>
    <NetFrameworkLts>net10.0</NetFrameworkLts>
    <DotNetLts>$(NetFrameworkLts)</DotNetLts>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(PrometheusEnabled)' == 'true'">
    <PrometheusLoadType Condition="'$(PrometheusLoadType)' == ''">Full</PrometheusLoadType>
    <!--<PrometheusTasksEnabled Condition="'$(PrometheusTasksEnabled)' == ''">True</PrometheusTasksEnabled>-->
    <SourceImportProps Condition="'$(SourceImportProps)' == ''"></SourceImportProps>
  </PropertyGroup>
  <PropertyGroup Label="Core directories and files" 
                 Condition="'$(PrometheusEnabled)' == 'true'">
    <PrometheusCommonDirectory>$(PrometheusDirectory)\Common</PrometheusCommonDirectory>
    <PrometheusCommonTargets>$(PrometheusCommonDirectory)\Common.Build.targets</PrometheusCommonTargets>
    <PrometheusCommonPackagesTargets>$(PrometheusCommonDirectory)\Common.Packages.targets</PrometheusCommonPackagesTargets>
    <PrometheusCommonProps>$(PrometheusCommonDirectory)\Common.Build.props</PrometheusCommonProps>
    <PrometheusImportertargets>$(PrometheusCommonDirectory)\Importer.Build.targets</PrometheusImportertargets>
    <PrometheusCoreDirectory>$(PrometheusDirectory)\Core</PrometheusCoreDirectory>
    <PrometheusCoreDefaultsProps>$(PrometheusCoreDirectory)\Core.Defaults.props</PrometheusCoreDefaultsProps>
    <PrometheusCoreDefaultsTargets>$(PrometheusCoreDirectory)\Core.Defaults.targets</PrometheusCoreDefaultsTargets>
    <PrometheusCorePackageProps>$(PrometheusCoreDirectory)\Core.Packaging.props</PrometheusCorePackageProps>
    <PrometheusCorePackageTargets>$(PrometheusCoreDirectory)\Core.Packaging.targets</PrometheusCorePackageTargets>
    <PrometheusReleaseTargets>$(PrometheusCoreDirectory)\Release.Build.targets</PrometheusReleaseTargets>
    <PrometheusDebugTargets>$(PrometheusCoreDirectory)\Debug.Build.targets</PrometheusDebugTargets>
    <!---->
    <PrometheusTestsProps>$(PrometheusCoreDirectory)\Tests.Build.props</PrometheusTestsProps>
    <PrometheusTestsTargets>$(PrometheusCoreDirectory)\Tests.Build.targets</PrometheusTestsTargets>
    <PrometheusCheckTargets>$(PrometheusDirectory)\Check.Build.targets</PrometheusCheckTargets>
    <PrometheusUsingsTargets>$(PrometheusDirectory)\Usings.Build.targets</PrometheusUsingsTargets>
  </PropertyGroup>

  <Choose>
    <When Condition="'$(PrometheusLoadType)' == 'full'">
      <PropertyGroup>
        <PrometheusPlatformEnabled Condition="'$(PrometheusPlatformEnabled)' == ''">True</PrometheusPlatformEnabled>
        <PrometheusImporterEnabled Condition="'$(PrometheusImporterEnabled)' == ''">True</PrometheusImporterEnabled>
        <PrometheusDetectionEnabled Condition="'$(PrometheusDetectionEnabled)' == ''">True</PrometheusDetectionEnabled>
        <!--<PrometheusPlatformEnabled Condition="'$(PrometheusTasksEnabled)' != 'true'">False</PrometheusPlatformEnabled>-->
        <PrometheusImportEnabled Condition="'$(PrometheusTasksEnabled)' != 'true'">False</PrometheusImportEnabled>
        <PrometheusPlatformDirectory>$(PrometheusDirectory)\Platform</PrometheusPlatformDirectory>
        <PrometheusRuntimeProps>$(PrometheusPlatformDirectory)\Runtime.Build.props</PrometheusRuntimeProps>
        <PrometheusRuntimetargets>$(PrometheusPlatformDirectory)\Runtime.Build.targets</PrometheusRuntimetargets>
        <PrometheusPlatformProps>$(PrometheusPlatformDirectory)\Platform.Build.props</PrometheusPlatformProps>
        <PrometheusPlatformtargets>$(PrometheusPlatformDirectory)\Platform.Build.targets</PrometheusPlatformtargets>
        <PrometheusDetectFrameworkProps>$(PrometheusPlatformDirectory)\Detect.Build.props</PrometheusDetectFrameworkProps>
        <PrometheusDetectFrameworkTargets>$(PrometheusPlatformDirectory)\Detect.Build.targets</PrometheusDetectFrameworkTargets>
      </PropertyGroup>
    </When>
    <When Condition="'$(PrometheusLoadType)' == 'lite'">

    </When>
    <Otherwise>

    </Otherwise>
  </Choose>

  <PropertyGroup Condition="'$(PrometheusTasksEnabled)' == 'true'">
    <SectionLength>40</SectionLength>
    <HeaderLength>40</HeaderLength>
    <SectionChar>=</SectionChar>
    <HeaderChar>~</HeaderChar>
  </PropertyGroup>

  <!--<PropertyGroup Condition="'$(TargetPlatform)' != '' And '$(TargetFramework)' == ''">
    <Array>$(TargetPlatform.Split(`-`))</Array>
    <RuntimeId>$(TargetPlatform.Split(`-`)[0])</RuntimeId>
    --><!--<TargetFramework>$(RuntimeId)</TargetFramework>--><!--
    --><!--Condition="'$(TargetPlatform.Split(`-`).Length)' &gt;= '2'"--><!--
    <PlatformId>$(TargetPlatform.Split(`-`)[1])</PlatformId>
    <TargetFramework Condition="'$(PlatformId)' != ''">$(RuntimeId)-$(PlatformId)</TargetFramework>
    --><!--<TargetFrameworks Condition="'$(TargetPlatforms)' != ''">$(TargetPlatforms)</TargetFrameworks>--><!--
  </PropertyGroup>-->
  <!--<PropertyGroup Condition="'$(PrometheusEnabled)' == 'true'">
    <BeforeTargetFrameworkInferenceTargets Condition="'$(IsTestProject)' == 'true'">$(BeforeTargetFrameworkInferenceTargets);$(PrometheusTestsProps)</BeforeTargetFrameworkInferenceTargets>
    <BeforeTargetFrameworkInferenceTargets Condition="Exists('$(PrometheusCoreDefaultsProps)')">$(BeforeTargetFrameworkInferenceTargets);$(PrometheusCoreDefaultsProps)</BeforeTargetFrameworkInferenceTargets>
  </PropertyGroup>-->

 <!-- <ImportGroup Condition="'$(PrometheusEnabled)' == 'true' And '$(PrometheusLoadType)' == 'lite'">
    
  </ImportGroup>-->
  
  <!--<Import Project="$(PrometheusCommonProps)" Condition="Exists('$(PrometheusCommonProps)')" />-->
  <!--<ItemGroup>
    <PackageReference Include="Prometheus.MSBuild.Tasks" Version="0.2.2-beta.27" PrivateAssets="all" IncludeAssets="all"/>
  </ItemGroup>
  <Import Project="$(LocalNugetRepoDirectory)" />-->
  <Target Name="_PrintPrometheusDefaultProps">
    <!--<ItemGroup>
      <MSBuildProjectParentDirectory Include="$(MSBuildProjectDirectory)\..\.." />
    </ItemGroup>-->
    <!--<PropertyGroup Condition="$(RootPath) == '' Or '$(SolutionDir)' == ''">
      <RootPath Condition="$(RootPath) == ''">$(SolutionDir)</RootPath>
      <SolutionDir Condition="'$(SolutionDir)' == ''">$(RootPath)\</SolutionDir>
    </PropertyGroup>-->
    <PropertyGroup>
      <SectionSymbol>*</SectionSymbol>
    </PropertyGroup>
    
    <!--<AttachDebuggerTask Condition="'$(PrometheusTasksEnabled)' == 'true' And '$(Configuration)' == 'debug'" />-->

    <Message Text="|" Importance="high" />
    <Message Text="| $(SectionString)" Importance="high" />
    <Message Text="| []==~ $(MSBuildThisFile) ~==[]" Importance="high" />
    <Message Text="| []==~- --Setting up Prometheus for $(MSBuildProjectName) $(TargetFramework)-- -~[]" Importance="high" />
    <Message Text="| $(HeaderString)" Importance="high" />
    
    <LogPropertyTask ProjectFiles="$(MSBuildThisFileFullPath)"
                     SectionSymbol="$(SectionSymbol)"
                     Condition="'$(PrometheusTasksEnabled)' == 'true'" />

    <Message Text="| $(SectionSymbol) RuntimeId: $(RuntimeId)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeVersion: $(RuntimeVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) HasPlatform: $(HasPlatform)" Importance="high" />
    <Message Text="| $(SectionSymbol) PlatformId: $(PlatformId)" Importance="high" />
    <Message Text="| $(SectionSymbol) PlatformVersion: $(PlatformVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeTargetFramework: $(RuntimeTargetFramework)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetPlatform: $(TargetPlatform)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetPlatforms: $(TargetPlatforms)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetFramework: $(TargetFramework)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetFrameworks: $(TargetFrameworks)" Importance="high" />

    <CallTarget Targets="PrintPrometheusNoTasks" Condition="'$(PrometheusTasksEnabled)' != 'true'" />
  </Target>

  <Target Name="PrintPrometheusNoTasks">
    <Message Text="| $(SectionSymbol) RootPath: $(RootPath)" Importance="high" />
    <Message Text="| $(SectionSymbol) SolutionDir: $(SolutionDir)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusDirectory: $(PrometheusDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusProps: $(PrometheusProps)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusTargets: $(PrometheusTargets)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusEnabled: $(PrometheusEnabled)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusAutoLoad: $(PrometheusAutoLoad)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusLoadType: $(PrometheusLoadType)" Importance="high" />
    <Message Text="| $(SectionSymbol) PrometheusPlatformEnabled: $(PrometheusPlatformEnabled)" Importance="high" />
  </Target>
</Project>
