<Project Sdk="Prometheus.MSBuild.Sdk/0.2.2-beta.31">
  <!--<Import Project="..\..\src\Prometheus.MSBuild\Sdk\Sdk.props" />-->
  <PropertyGroup>
    <ProductName>Net6.Tests</ProductName>
    <TargetPlatform>net8.0</TargetPlatform>
    <!--<IsTestProject>True</IsTestProject>-->
    <IsLibraryProject>True</IsLibraryProject>   
    <!--<PrometheusTasksEnabled>false</PrometheusTasksEnabled>-->
  </PropertyGroup>
  <!--k<Import Project="..\..\src\Prometheus.MSBuild\Sdk\Sdk.targets" />-->
</Project>
