<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <DisableMSBuildAssemblyCopyCheck>True</DisableMSBuildAssemblyCopyCheck>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="17.10.4" />
    <PackageReference Include="Microsoft.Build.Engine" Version="17.10.4" />
    <PackageReference Include="Microsoft.Build.Framework" Version="17.10.4" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.10.4" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="17.10.4" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.7.8" />
    <PackageReference Include="Nuget.Frameworks" Version="6.0.0" />
    <PackageReference Include="Nuget.ProjectModel" Version="6.0.0" />
    <PackageReference Include="Shin.Framework" Version="0.1.6-beta.18" />
    <PackageReference Include="Prometheus.MSBuild.Tasks" Version="0.2.2-beta.27" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Prometheus.MSBuild.Tasks">
      <HintPath>..\..\build\bin\Debug\net48\Prometheus.MSBuild.Tasks.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="..\resources\Imports.Build.props">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="..\resources\Test.Build.props">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="..\resources\Test.projitems">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!--<Import Project="..\..\src\Prometheus.MSBuild.Tasks\Prometheus.Tasks.projitems" Label="Shared" />-->

</Project>
