<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="_PrintPrometheusGlobals">
  <!--<PropertyGroup>
    <Product Condition="'$(Product)' == '' 
        And '$(ProductName)' != ''">$(ProductName)</Product>
    <CopyrightStartYear Condition="'$(CopyrightStartYear)' == ''">1900</CopyrightStartYear>
    <AssemblyName Condition="'$(AssemblyName)' == '' 
        And '$(Product)' != ''">$(Product)</AssemblyName>
    <Company Condition="'$(Company)' == ''
        And '$(CompanyName)' != ''">$(CompanyName)</Company>
    <Authors Condition="'$(AuthorName)' != ''">$(AuthorName);$(Authors)</Authors>
    <Owners Condition="'$(Owners)' != ''">$(Company);$(Owners)</Owners>
    <Copyright>copyright © $(CompanyName) $(CopyrightStartYear)-$([System.DateTime]::Now.Year)</Copyright>
    <Version Condition="'$(Version)' == ''
        And '$(ProductVersion)' != ''">$(ProductVersion)</Version>
    <FileVersion Condition="'$(FileVersion)' == ''
        And '$(Version)' != ''">$(Version)</FileVersion>
  </PropertyGroup>-->
  <PropertyGroup>
    <!--<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductName Condition=" '$(ProductName)' == '' ">My Application</ProductName>
    <CompanyName Condition=" '$(CompanyName)' == '' ">My Company</CompanyName>
    <AuthorName Condition=" '$(AuthorName)' == '' ">$(UserName)</AuthorName>
    <ProductVersion Condition=" '$(ProductVersion)' == '' ">0.0.1</ProductVersion>-->
    <!--<IsSharedProject Condition=" '$(IsSharedProject)' == '' ">$(MSBuildProjectExtension.Contains('shproj'))</IsSharedProject>
    <IsTestProject Condition=" '$(IsTestProject)' == '' ">False</IsTestProject>
    <IsLibraryProject Condition=" '$(IsLibraryProject)' == '' "></IsLibraryProject>
    <MergeBinary Condition=" '$(MergeBinary)' == '' "></MergeBinary>
    <UseGitHub Condition="'$(UseGitHub)' == ''">False</UseGitHub>
    <FirstTimeLoading Condition=" '$(FirstTimeLoading)' == '' ">True</FirstTimeLoading>
    <IsPackable Condition="'$(IsPackable)' == ''">False</IsPackable>
    <EnableNETAnalyzers Condition="'$(EnableNETAnalyzers)' == ''">True</EnableNETAnalyzers>
    <SetupCompleted Condition=" '$(SetupCompleted)' == '' ">False</SetupCompleted>
    <TargetPlatform Condition=" '$(TargetPlatform)' == '' And '$(TargetPlatforms)' != ''">net6.0</TargetPlatform>
    <PlatformId Condition=" '$(PlatformId)' == '' ">None</PlatformId>
    <Description Condition="'$(Description)' == ''">Description</Description>
    <IsPackageOnlyProject Condition="'$(IsPackageOnlyProject)' == ''"></IsPackageOnlyProject>
    <UseImportCache Condition="'$(UseImportCache)' == ''">True</UseImportCache>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <HasTests Condition="'$(HasTests)' == ''">False</HasTests>
    <DisableExtraReferences>true</DisableExtraReferences>-->
  </PropertyGroup>
  
  <PropertyGroup Condition="$(SolutionDir) != ''">
    <SourceDirectory Condition=" '$(SourceDirectory)' == '' ">$(SolutionDir)src</SourceDirectory>
    <ThirdPartyDirectory Condition=" '$(ThirdPartyDirectory)' == '' ">$(SolutionDir)third-party</ThirdPartyDirectory>
    <BuildDirectory Condition="'$(BuildDirectory)' == ''">$(SolutionDir)build</BuildDirectory>
    <PrometheusDirectory Condition=" '$(PrometheusDirectory)' == '' ">$(PrometheusDirectory)\Prometheus</PrometheusDirectory>
    <SolutionProps Condition=" '$(SolutionProps)' == '' ">$(SolutionDir)Solution.Build.props</SolutionProps>
    <SolutionTargets Condition=" '$(SolutionTargets)' == '' ">$(SolutionDir)Solution.Build.targets</SolutionTargets>
    <UserProps Condition=" '$(UserProps)' == '' ">$(SolutionDir)User.Build.props</UserProps>
    <UserTargets Condition=" '$(UserTargets)' == '' ">$(SolutionDir)User.Build.targets</UserTargets>
    <SolutionImportProps Condition="'$(SolutionImportProps)' == ''">$(SolutionDir)Imports.Build.props</SolutionImportProps>
  </PropertyGroup>
  
  <!--And '$(AssemblyName)' != ''
  And '$(Configuration)' != ''-->
  <PropertyGroup
    Condition="'$(BuildDirectory)' != ''">
    <_ArtifactsPathSetEarly>true</_ArtifactsPathSetEarly>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(BuildDirectory)</ArtifactsPath>
    <!--<OutputPath>$(OutputDirectory)</OutputPath>-->
    <!--<OutputDirectory>$(BuildDirectory)\bin\$(Configuration)\$(AssemblyName)</OutputDirectory>-->
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)' != ''">$(BaseIntermediateOutputPath)\$(Configuration)</BaseIntermediateOutputPath>
  </PropertyGroup>
  
  
  
  <Import Project="$(SolutionProps)" Condition="Exists($(SolutionProps))"/>
  <Import Project="$(UserProps)" Condition="Exists($(UserProps))" />
  <!--<Import Project="($(PrometheusTestsProps)" Condition="('$(IsTestProject)' == 'true' Or '$(HasTests)' == 'true') 
      And Exists($(PrometheusTestsProps))" />-->

  <PropertyGroup>
    <PrometheusCoreDefaultsPropsLoaded>true</PrometheusCoreDefaultsPropsLoaded>
  </PropertyGroup>
  
  <Target Name="_PrintPrometheusGlobals">
    <PropertyGroup>
      <SectionSymbol>%</SectionSymbol>
    </PropertyGroup>

    <Message Text="| $(SectionString)" Importance="high" />
    <Message Text="$~----------------------------" Importance="high" />
    <Message Text="$~----- Getting Global Variables for $(MSBuildProjectName) ------~$" Importance="high" />
    <Message Text="| []==~ $(MSBuildThisFile) ~==[]" Importance="high" />
    <Message Text="| $(HeaderString)" Importance="high" />
    
    <Error Condition="'$(BuildDirectory)' == ''" Text="Solution Build Directory /$/(BuildDiredtory/) is not set" />
    <LogPropertyTask ProjectFiles="$(PrometheusCoreDefaultsProps);$(PrometheusCoreDefaultsTargets)" 
                     SectionSymbol="$(SectionSymbol)" 
                     Condition="'$(PrometheusTasksEnabled)' == 'true'"/>

    <Message Text="| $(SectionSymbol) ProductName: $(ProductName)" Importance="high" />
    <Message Text="| $(SectionSymbol) AssemblyName: $(AssemblyName)" Importance="high" />
    <Message Text="| $(SectionSymbol) CompanyName: $(CompanyName)" Importance="high" />
    <Message Text="| $(SectionSymbol) AuthorName: $(AuthorName)" Importance="high" />
    <Message Text="| $(SectionSymbol) ProductVersion: $(ProductVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) Version: $(Version)" Importance="high" />
    <Message Text="| $(SectionSymbol) PackageVersion: $(PackageVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeId: $(RuntimeId)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeVersion: $(RuntimeVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) PlatformId: $(PlatformId)" Importance="high" />
    <Message Text="| $(SectionSymbol) PlatformVersion: $(PlatformVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeTargetFramework: $(RuntimeTargetFramework)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetPlatform: $(TargetPlatform)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetPlatforms: $(TargetPlatforms)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetFramework: $(TargetFramework)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetFrameworks: $(TargetFrameworks)" Importance="high" />
    <Message Text="| $(SectionSymbol) AutoDetectPlatform: $(AutoDetectPlatform)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsPackable: $(IsPackable)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsSharedProject: $(IsSharedProject)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsTestProject: $(IsTestProject)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsLibraryProject: $(IsLibraryProject)" Importance="high" />
    <Message Text="| $(SectionSymbol) MSBuildProjectExtension: $(MSBuildProjectExtension)" Importance="high" />
    <Message Text="| $(SectionSymbol) MSBuildThisFileDirectory: $(MSBuildThisFileDirectory)" Importance="high" />

    <Message Text="| $(SectionSymbol) SolutionDir: $(SolutionDir)" Importance="high" />
    <Message Text="| $(SectionSymbol) SourceDirectory: $(SourceDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) ThridPartyDirectory: $(ThriPartyDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) BuildDirectory: $(BuildDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) OutputDirectory: $(OutputDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) OutputPath: $(OutputPath)" Importance="high" />
    <Message Text="| $(SectionSymbol) BaseIntermediateOutputPath: $(BaseIntermediateOutputPath)" Importance="high" />
    <Message Text="| $(SectionSymbol) TestsDirectory: $(TestsDirectory)" Importance="high" />
    
    <Message Text="| $(SectionSymbol) SharedImports: $(SharedImports)" Importance="high" />
  </Target>
</Project>
