<Project InitialTargets="_PrintPrometheusGlobals2">
  <!--<Import Project="$(PrometheusCoreDefaultsProps)" Condition="Exists('$(PrometheusCoreDefaultsProps)')
      And '$(PrometheusCoreDefaultsPropsLoaded)' != 'true'" />-->
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductName Condition=" '$(ProductName)' == '' ">My Application</ProductName>
    <CompanyName Condition=" '$(CompanyName)' == '' ">My Company</CompanyName>
    <AuthorName Condition=" '$(AuthorName)' == '' ">$(UserName)</AuthorName>
    <ProductVersion Condition=" '$(ProductVersion)' == '' ">0.0.1</ProductVersion>
    <!--<IsSharedProject Condition=" '$(IsSharedProject)' == '' ">$(MSBuildProjectExtension.Contains('shproj'))</IsSharedProject>
    <IsTestProject Condition=" '$(IsTestProject)' == '' ">False</IsTestProject>
    <IsLibraryProject Condition=" '$(IsLibraryProject)' == '' "></IsLibraryProject>
    <MergeBinary Condition=" '$(MergeBinary)' == '' "></MergeBinary>
    <UseGitHub Condition="'$(UseGitHub)' == ''">False</UseGitHub>
    <FirstTimeLoading Condition=" '$(FirstTimeLoading)' == '' ">True</FirstTimeLoading>
    <IsPackable Condition="'$(IsPackable)' == ''">False</IsPackable>
    <EnableNETAnalyzers Condition="'$(EnableNETAnalyzers)' == ''">True</EnableNETAnalyzers>
    <SetupCompleted Condition=" '$(SetupCompleted)' == '' ">False</SetupCompleted>
    <TargetPlatform Condition=" '$(TargetPlatform)' == '' And '$(TargetPlatforms)' != ''">net6.0</TargetPlatform>
    <PlatformId Condition=" '$(PlatformId)' == '' ">None</PlatformId>
    <Description Condition="'$(Description)' == ''">Description</Description>
    <IsPackageOnlyProject Condition="'$(IsPackageOnlyProject)' == ''"></IsPackageOnlyProject>
    <UseImportCache Condition="'$(UseImportCache)' == ''">True</UseImportCache>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <HasTests Condition="'$(HasTests)' == ''">False</HasTests>
    <DisableExtraReferences>true</DisableExtraReferences>-->
  </PropertyGroup>
  <PropertyGroup>
    <Product Condition="'$(ProductName)' != ''">$(ProductName)</Product>
    <CopyrightStartYear Condition="'$(CopyrightStartYear)' == ''">1900</CopyrightStartYear>
    <AssemblyName Condition="'$(Product)' != ''">$(Product)</AssemblyName>
    <Company Condition="'$(CompanyName)' != ''">$(CompanyName)</Company>
    <Authors Condition="'$(AuthorName)' != ''">$(AuthorName);$(Authors)</Authors>
    <Owners Condition="'$(Owners)' != ''">$(Company);$(Owners)</Owners>
    <Copyright>copyright © $(CompanyName) $(CopyrightStartYear)-$([System.DateTime]::Now.Year)</Copyright>
    <Version Condition="'$(ProductVersion)' != ''">$(ProductVersion)</Version>
    <FileVersion Condition="'$(Version)' != ''">$(Version)</FileVersion>
  </PropertyGroup>
  <!--<PropertyGroup Condition="$(SolutionDir) != ''">
    <SourceDirectory Condition=" '$(SourceDirectory)' == '' ">$(SolutionDir)src</SourceDirectory>
    <ThirdPartyDirectory Condition=" '$(ThirdPartyDirectory)' == '' ">$(SolutionDir)third-party</ThirdPartyDirectory>
    <BuildDirectory Condition="'$(BuildDirectory)' == ''">$(SolutionDir)build</BuildDirectory>
    <PrometheusDirectory Condition=" '$(PrometheusDirectory)' == '' ">$(PrometheusDirectory)\Prometheus</PrometheusDirectory>
    <SolutionProps Condition=" '$(SolutionProps)' == '' ">$(SolutionDir)Solution.Build.props</SolutionProps>
    <UserProps Condition=" '$(UserProps)' == '' ">$(SolutionDir)User.Build.props</UserProps>
    <SolutionImportProps Condition="'$(SolutionImportProps)' == ''">$(SolutionDir)Imports.Build.props</SolutionImportProps>
  </PropertyGroup>-->

  <!--<PropertyGroup
    Condition="'$(BuildDirectory)' != ''
        And '$(AssemblyName)' != ''
        And '$(Configuration)' != ''">
    <OutputDirectory>$(BuildDirectory)\bin\$(Configuration)\$(AssemblyName)</OutputDirectory>
    <OutputPath>$(OutputDirectory)</OutputPath>
    <BaseIntermediateOutputPath>$(BuildDirectory)\obj\$(AssemblyName)</BaseIntermediateOutputPath>
  </PropertyGroup>-->
  
  <Import Project="$(SolutionTargets)" Condition="Exists($(SolutionTargets))" />
  <Import Project="$(UserTargets)" Condition="Exists($(UserTargets))" />
  <!--<Import Project="($(PrometheusTestsTargets)" Condition="('$(IsTestProject)' == 'true' 
      Or '$(HasTests)' == 'true') 
      And Exists($(PrometheusTestsTargets))" />-->
  <Import Project="$(PrometheusDebugTargets)" 
          Condition="'$(Configuration)' == 'debug'
          And Exists('$(PrometheusDebugTargets)')" />

  <PropertyGroup Condition="'$(IsMSBuildTaskLibraryProject)' == 'true'">
    <IsLibraryProject>true</IsLibraryProject>
    <!-- This target will run when MSBuild is collecting the files to be packaged, and we'll implement it below. This property controls the dependency list for this packaging process, so by adding our custom property we hook ourselves into the process in a supported way. -->
    <TargetsForTfmSpecificBuildOutput>
      $(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage
    </TargetsForTfmSpecificBuildOutput>
    <!-- This property tells MSBuild where the root folder of the package's build assets should be. Because we are not a library package, we should not pack to 'lib'. Instead, we choose 'tasks' by convention. -->
    <BuildOutputTargetFolder>tasks</BuildOutputTargetFolder>
    <!-- NuGet does validation that libraries in a package are exposed as dependencies, but we _explicitly_ do not want that behavior for MSBuild tasks. They are isolated by design. Therefore we ignore this specific warning. -->
    <NoWarn>NU5100</NoWarn>
    <!-- Suppress NuGet warning NU5128. -->
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>
  
  <PropertyGroup Label="Configure assembly names and namespaces">
    <!--<TargetFrameworks>netstandard2.1;net5.0;netcoreapp3.1</TargetFrameworks>-->
    <RootNamespace Condition="'$(RootNamespace)' == ''">$(AssemblyName)</RootNamespace>
    <!--<GenerateAssemblyInfo>true</GenerateAssemblyInfo>-->
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsLibraryProject)' == 'true'">
    <OutputType>Library</OutputType>
    <DocumentationFile>$(OutputDirectory)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Normalize stack trace file locations" Condition="$(BuildingInsideVisualStudio) != 'true'
      And Exists('$(SourceDirectory)')">
    <PathMap>$([System.IO.Path]::GetFullPath('$(SolutionDir)'))=X:\</PathMap>
  </PropertyGroup>

  <Target Name="_PrintPrometheusGlobals2">
    <PropertyGroup>
      <SectionSymbol>%</SectionSymbol>
    </PropertyGroup>

    <Message Text="| $(SectionString)" Importance="high" />
    <Message Text="| []==~ $(MSBuildThisFile) ~==[]" Importance="high" />
    <Message Text="| $(HeaderString)" Importance="high" />

    <!--<ItemGroup Condition="'$(TargetPlatforms)' != ''">
      <TPlatforms Include="$(TargetPlatforms.Split(`;`))" />
    </ItemGroup>
    <PropertyGroup Condition="'$(TargetPlatforms)' != ''">
      <TargetPlatform>%(TPlatforms.Identity)</TargetPlatform>
      <TargetFramework>%(TPlatforms.Identity)</TargetFramework>
    </PropertyGroup>-->
    
    <LogPropertyTask ProjectFiles="$(MSBuildThisFileFullPath)" SectionSymbol="$(SectionSymbol)"
                     Condition="'$(PrometheusTasksEnabled)' == 'true'" />

    <Message Text="| $(SectionSymbol) ProductName: $(ProductName)" Importance="high" />
    <Message Text="| $(SectionSymbol) AssemblyName: $(AssemblyName)" Importance="high" />
    <Message Text="| $(SectionSymbol) CompanyName: $(CompanyName)" Importance="high" />
    <Message Text="| $(SectionSymbol) AuthorName: $(AuthorName)" Importance="high" />
    <Message Text="| $(SectionSymbol) ProductVersion: $(ProductVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) Version: $(Version)" Importance="high" />
    <Message Text="| $(SectionSymbol) PackageVersion: $(PackageVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeId: $(RuntimeId)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeVersion: $(RuntimeVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) PlatformId: $(PlatformId)" Importance="high" />
    <Message Text="| $(SectionSymbol) PlatformVersion: $(PlatformVersion)" Importance="high" />
    <Message Text="| $(SectionSymbol) RuntimeTargetFramework: $(RuntimeTargetFramework)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetPlatform: $(TargetPlatform)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetPlatforms: $(TargetPlatforms)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetFramework: $(TargetFramework)" Importance="high" />
    <Message Text="| $(SectionSymbol) TargetFrameworks: $(TargetFrameworks)" Importance="high" />
    <Message Text="| $(SectionSymbol) AutoDetectPlatform: $(AutoDetectPlatform)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsPackable: $(IsPackable)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsSharedProject: $(IsSharedProject)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsTestProject: $(IsTestProject)" Importance="high" />
    <Message Text="| $(SectionSymbol) IsLibraryProject: $(IsLibraryProject)" Importance="high" />
    <Message Text="| $(SectionSymbol) MSBuildProjectExtension: $(MSBuildProjectExtension)" Importance="high" />
    <Message Text="| $(SectionSymbol) MSBuildThisFileDirectory: $(MSBuildThisFileDirectory)" Importance="high" />

    <Message Text="| $(SectionSymbol) SolutionDir: $(SolutionDir)" Importance="high" />
    <Message Text="| $(SectionSymbol) SourceDirectory: $(SourceDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) ThridPartyDirectory: $(ThriPartyDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) BuildDirectory: $(BuildDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) OutputDirectory: $(OutputDirectory)" Importance="high" />
    <Message Text="| $(SectionSymbol) BaseIntermediateOutputPath: $(BaseIntermediateOutputPath)" Importance="high" />
    <Message Text="| $(SectionSymbol) TestsDirectory: $(TestsDirectory)" Importance="high" />
    
    <Message Text="| $(SectionSymbol) SharedImports: $(SharedImports)" Importance="high" />
  </Target>
</Project>
